export const projects = [
  {
    title: 'Threads Social App',
    description: 'This is a full-stack application that I created to practice the MERN Stack. It utilizes ShadCN and incorporates the Clerk authentication system.',
    image: '/images/threads.jpg',
      tags: ['MongoDB', 'Express', 'React', 'Node', 'TypeScript'],
    source: 'https://threads-iota-nine.vercel.app/',
    visit: 'https://github.com/Gab0CS/threads',
    id: 0,
  },
  {
    title: 'Fiubags',
    description: 'I am currently working on an ecommerce project where my responsibility is to restructure the user interfaces to enhance the overall user experience (UX) and improve conversions.',
    image: '/images/fiubags.jpg',
      tags: ['Laravel', 'JavaScript', 'Boostrap', 'Linux'],
    source: 'https://fiubags.mx/',
    visit: '#!',
    id: 1,
  },
  {
    title: 'Adopt a Pet',
    description: 'To assist a pet shelter with the adoption process, I developed a React web app. This web application guides you through various types of pets using the React-Router library, providing a seamless Single Page Application (SPA) experience.',
    image: '/images/adopt.jpg',
    tags: ['React','React-Router', 'JavaScript'],
    source: 'https://inquisitive-dragon-9de480.netlify.app/',
    visit: 'https://github.com/Gab0CS/adopt-a-pet-project',
    id: 1,
  },
  {
    title: 'Appointment planner',
    description: "This is a React app that I created to implement my knowledge of React hooks and stateful and stateless functional component patterns. It serves as an appointment planner to assist you in organizing your time effectively.",
      image: '/images/appointments.jpg',
      tags: ['React', 'JavaScript'],
    source: 'https://regal-travesseiro-8d3af2.netlify.app',
    visit: 'https://github.com/Gab0CS/react_challenge_start',
    id: 2,
  },
  {
    title: 'Jamming',
    description: "This is a Web app made with React, it lets you to create a playlist and save it into your spotify account by using the Spotify API.",
    image: '/images/jamming.jpg',
    tags: ['React', 'JavaScript', 'API'],
    source: 'https://tourmaline-genie-ad354e.netlify.app/',
    visit: 'https://github.com/Gab0CS/jamming',
    id: 3,
  },
  {
    title: 'Piano keys',
    description: "This is an interactive piano page to follow the 'Happy Birthday' song",
    image: '/images/pianokeys.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://pianokeys.surge.sh/',
    visit: 'https://github.com/Gab0CS/pianokeys',
    id: 3,
  }
];

export const TimeLineData = [
  { year: 2018, text: 'Started the college.', },
  { year: 2019, text: 'My interest in programming and the IT world began.', },
  { year: 2020, text: 'Finished all the freeCodeCamp courses.', },
  { year: 2021, text: 'Worked as Production Analyst where I developed a CRUD App for production control.', },
  { year: 2022, text: 'Worked as data Analyst intern.', },
  { year: 2022, text: 'Completed the college.', },
  { year: 2023, text: 'Working at Brandbackers as Web Developer.', },
];